[package]
name = "bevy_state_plugin_generator"
version = "1.1.0-alpha.1"
edition = "2024"
license = "MIT"
description = "A build-dependency that generates a Bevy State Plugin from a simple state definition."
repository = "https://github.com/rmvermeulen/bevy-state-plugin-generator.git"

[lib]

[[bin]]
name = "bspgen"


[features]
default = ["all"]
all = ["rustfmt"]      # "comments", "lists"
lists = []
comments = []
rustfmt = ["dep:duct"]

[dependencies]
derive_more = { version = "2.0.1", features = [
    "deref",
    "deref_mut",
    "as_ref",
    "from",
] }
duct = { version = "0.13.7", optional = true }
indoc = "2.0.5"
iter_tools = "0.24.0"
nom = "8.0.0"

[dev-dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
insta = "1.42.1"
rstest = "0.24.0"
speculoos = "0.11.0"
tempfile = "3.16.0"

[dev-dependencies.bevy]
version = "0.15.2"
default-features = false
features = ["bevy_state"]
