[package]
name = "bevy_state_plugin_generator"
version = "0.15.0"
edition = "2024"

[lib]

[[bin]]
name = "bspgen"

[dependencies]
iter_tools = "0.24.0"

[dev-dependencies]
insta = "1.42.1"
rstest = "0.24.0"
speculoos = "0.11.0"
