[package]
name = "bevy_state_plugin_generator"
version = "0.15.0"
edition = "2024"

[lib]

[[bin]]
name = "bspgen"


[features]
default = ["full"]
full = ["parse", "generate", "format"]
parse = []
generate = []
format = ["dep:duct"]

[dependencies]
duct = { version = "0.13.7", optional = true }
iter_tools = "0.24.0"

[dev-dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
insta = "1.42.1"
rstest = "0.24.0"
speculoos = "0.11.0"
tempfile = "3.2.0"
