[package]
name = "bevy_state_plugin_generator"
version = "1.0.2-dev"
edition = "2024"
license = "MIT"
description = "A build-dependency that generates a Bevy State Plugin from a simple state definition."

[lib]

[[bin]]
name = "bspgen"


[features]
default = ["full"]
full = ["parse", "generate", "format"]
parse = []
generate = []
format = ["dep:duct"]

[dependencies]
derive_more = { version = "2.0.1", features = [
  "deref",
  "deref_mut",
  "as_ref",
  "from",
] }
duct = { version = "0.13.7", optional = true }
iter_tools = "0.24.0"
nom = "8.0.0"

[dev-dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
insta = "1.42.1"
rstest = "0.24.0"
speculoos = "0.11.0"
tempfile = "3.16.0"

[dev-dependencies.bevy]
version = "0.15.2"
default-features = false
features = ["bevy_state"]

[build-dependencies]
bevy_state_plugin_generator = { version = "1.0.1", features = ["full"] }
