[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run-headless]
command = "cargo"
args = ["run"]

[tasks.test]
install_crate = "cargo-insta"
command = "cargo"
args = ["insta", "test", "--unreferenced=warn"]

[tasks.review]
install_crate = "cargo-insta"
command = "cargo"
# do not use nextest for snapshot test+review, it breaks something
args = ["insta", "review"]

[tasks.cover]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "nextest"]

[tasks.generate-report]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--doctests", "--html"]

[tasks.replace-report]
cwd = "."
script = """
    #!/bin/bash
    set -exu
    # clean old report
    rm -rf report/
    # copy new report
    cp -r target/llvm-cov/html report/
    # format using prettier
    npx -y prettier --write report/
    # remove `Created` timestamps
    fd -tf html report | xargs sed -i 's/<h4>Created.\\+<\\/h4>//'
"""

[tasks.report]
run_task = [{ name = ["generate-report", "replace-report"] }]
