[config]
default_to_workspace = false

[tasks.test]
clear = true
run_task = { name = ["test-lib", "test-app"] }

[tasks.test-lib]
install_crate = "cargo-feature-combinations"
command = "cargo-feature-combinations"
args = ["insta", "test"]

[tasks.review]
install_crate = "cargo-insta"
command = "cargo"
# do not use nextest for snapshot test+review, it breaks something
args = ["insta", "review"]

[tasks.cover]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--doctests"]

[tasks.report]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--doctests", "--html", "--open"]

[tasks.test-app-build]
cwd = "test-app/"
command = "cargo"
args = ["build", "--release"]

[tasks.test-app-test]
install_crate = "cargo-insta"
cwd = "test-app/"
command = "cargo"
args = ["insta", "test", "--unreferenced=warn"]

[tasks.test-app]
run_task = [{ name = ["test-app-build", "test-app-test"] }]
