[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run-headless]
command = "cargo"
args = ["run"]

[tasks.test]
install_crate = "cargo-insta"
command = "cargo"
args = ["insta", "test", "--unreferenced=warn"]

[tasks.review]
install_crate = "cargo-insta"
command = "cargo"
# do not use nextest for snapshot test+review, it breaks something
args = ["insta", "review"]

[tasks.cover]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "nextest"]

[tasks.generate-report]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--doctests", "--html"]

[tasks.copy-report]
command = "cp"
args = ["-r", "target/llvm-cov/html", "report"]

[tasks.clean-report]
command = "rm"
args = ["-rf", "report/"]

[tasks.format-report]
command = "npx"
args = ["-y", "prettier", "--write", "report/"]

[tasks.report]
run_task = [
    { name = [
        "generate-report",
        "clean-report",
        "copy-report",
        "format-report",
    ] },
]
