[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run-headless]
command = "cargo"
args = ["run"]

[tasks.test]
install_crate = "cargo-insta"
command = "cargo"
args = ["insta", "test", "--unreferenced=warn"]

[tasks.review]
install_crate = "cargo-insta"
command = "cargo"
# do not use nextest for snapshot test+review, it breaks something
args = ["insta", "review"]

[tasks.cover]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "nextest"]
