#!/usr/bin/env bash

set -eu
echo "Pre-commit hook"

unformatted=$(cargo fmt --check --message-format short | ag -v generated_states || exit 0)

if [ ! -z "$unformatted" ]; then
	echo "Unformatted files!"
	echo "$unformatted"
	exit 1
fi

# also build test-app in relevant feature combinations
just build

# test until first error
just test-fast
