#!/usr/bin/env bash

set -exu
echo "Pre-push hook"
cargo fmt --check

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" != "main" ]; then
	cargo-feature-combinations test
	exit 0
fi

cargo make --no-workspace report
status=$(git status -s)
if [ -n "$status" ]; then
	echo "You have uncommitted changes; aborting push"
	exit 1
fi
