// generated by bevy_state_plugin_generator v1.4.1
// WARN: unknown setting: 'nonsense'
// bspg:nonsense 123
// bspg:root_state_name RootState
// bspg:naming_scheme   Full
// bspg:
// Loading {
//     Configs
//     Assets
// }
// Ready {
//     Playing
//     Paused
// }
// Exiting

use bevy::prelude::AppExtStates;
#[allow(missing_docs)]
pub mod states {
    use bevy::prelude::StateSet;
    #[derive(bevy::prelude::States, Hash, Default, Debug, Clone, PartialEq, Eq)]
    pub enum RootState {
        #[default]
        Loading,
        Ready,
        Exiting,
    }

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(RootState = RootState::Loading)]
    pub enum RootStateLoading {
        #[default]
        Configs,
        Assets,
    }

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(RootState = RootState::Ready)]
    pub enum RootStateReady {
        #[default]
        Playing,
        Paused,
    }

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(RootState = RootState::Exiting)]
    pub struct RootStateExiting;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(RootStateLoading = RootStateLoading::Configs)]
    pub struct RootStateLoadingConfigs;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(RootStateLoading = RootStateLoading::Assets)]
    pub struct RootStateLoadingAssets;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(RootStateReady = RootStateReady::Playing)]
    pub struct RootStateReadyPlaying;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(RootStateReady = RootStateReady::Paused)]
    pub struct RootStateReadyPaused;
}
pub struct GeneratedStatesPlugin;
impl bevy::app::Plugin for GeneratedStatesPlugin {
    fn build(&self, app: &mut bevy::app::App) {
        app.init_state::<states::RootState>()
            .add_sub_state::<states::RootStateLoading>()
            .add_sub_state::<states::RootStateReady>()
            .add_sub_state::<states::RootStateExiting>()
            .add_sub_state::<states::RootStateLoadingConfigs>()
            .add_sub_state::<states::RootStateLoadingAssets>()
            .add_sub_state::<states::RootStateReadyPlaying>()
            .add_sub_state::<states::RootStateReadyPaused>();
    }
}
