// generated by bevy_state_plugin_generator v1.3.0-beta
// src: src/states.txt
// Loading {
//     Configs
//     Assets
// }
// Ready {
//     Playing
//     Paused
// }
// Exiting

#![allow(missing_docs)]
use bevy::prelude::AppExtStates;
pub mod states {
    use bevy::prelude::StateSet;
    #[derive(bevy::prelude::States, Hash, Default, Debug, Clone, PartialEq, Eq)]
    pub enum GameState {
        #[default]
        Loading,
        Ready,
        Exiting,
    }

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(Game = Game::Loading)]
    pub enum GameLoading {
        #[default]
        Configs,
        Assets,
    }

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(GameLoading = GameLoading::Configs)]
    pub struct GameLoadingConfigs;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(GameLoading = GameLoading::Assets)]
    pub struct GameLoadingAssets;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(Game = Game::Ready)]
    pub enum GameReady {
        #[default]
        Playing,
        Paused,
    }

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(GameReady = GameReady::Playing)]
    pub struct GameReadyPlaying;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(GameReady = GameReady::Paused)]
    pub struct GameReadyPaused;

    #[derive(bevy::prelude::SubStates, Hash, Default, Debug, Clone, PartialEq, Eq)]
    #[source(Game = Game::Exiting)]
    pub struct GameExiting;
}
pub struct GeneratedStatesPlugin;
impl bevy::app::Plugin for GeneratedStatesPlugin {
    fn build(&self, app: &mut bevy::app::App) {
        app.init_state::<states::GameState>()
            .add_sub_state::<states::GameLoading>()
            .add_sub_state::<states::GameLoadingConfigs>()
            .add_sub_state::<states::GameLoadingAssets>()
            .add_sub_state::<states::GameReady>()
            .add_sub_state::<states::GameReadyPlaying>()
            .add_sub_state::<states::GameReadyPaused>()
            .add_sub_state::<states::GameExiting>();
    }
}
